name: Set up Flutter
description: Setup your runner with Flutter environment
author: Alif Rachmawadi
branding:
  icon: maximize
  color: blue

inputs:
  flutter-version:
    description: The Flutter version to make available on the path
    required: false
    default: ""
  cache:
    description: Cache the Flutter SDK
    required: false
    default: "false"
  cache-key:
    description: Identifier for the Flutter SDK cache
    required: false
    default: ""
  cache-path:
    description: Flutter SDK cache path
    required: false
    default: "flutter-folder"
  pub-cache-key:
    description: Identifier for the Dart .pub-cache cache
    required: false
    default: ""
  pub-cache-path:
    description: Flutter pub cache path
    required: false
    default: "pubcache"
  git-source:
    description: Git clone source
    required: false
    default: "https://github.com/flutter/flutter.git"

outputs:
  VERSION:
    value: "${{ steps.flutter-action.outputs.VERSION }}"
    description: The selected Flutter version
  CACHE-KEY:
    value: "${{ steps.flutter-action.outputs.CACHE-KEY }}"
    description: Key used to cache the Flutter SDK
  CACHE-PATH:
    value: "${{ steps.flutter-action.outputs.CACHE-PATH }}"
    description: Path to Flutter SDK
  PUB-CACHE-KEY:
    value: "${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}"
    description: Key used to cache the pub dependencies
  PUB-CACHE-PATH:
    value: "${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}"
    description: Path to pub cache
  GIT_SOURCE:
    value: "${{ steps.flutter-action.outputs.GIT_SOURCE }}"
    description: Git source of Flutter SDK repository to clone

runs:
  using: composite
  steps:
    # This is a cross-platform composite action that needs yq.
    # It's not preinstalled on Windows runners.
    # See https://github.com/actions/runner-images/issues/7443#issuecomment-1514597691
    - name: Make yq tool available on Windows runners
      if: runner.os == 'Windows'
      run: choco install yq
      shell: bash

    - name: Set action inputs
      id: flutter-action
      shell: bash
      run: |
        rm -rf /var/lib/apt/lists/* /tmp/* /var/cache/apt/* \
          /usr/share/man/* /usr/share/doc/*

        mkdir -p ${{ inputs.cache-path }} ${{ inputs.pub-cache-path }}
        git clone -b ${{ inputs.flutter-version }} --depth 1 ${{ inputs.git-source }} ${{ inputs.cache-path }}
        cd ${{ inputs.cache-path }}
        git config --global --add safe.directory ${{ inputs.cache-path }} 
        git gc --aggressive --prune=all 
        flutter config --disable-analytics --no-cli-animations
        flutter precache --universal 
        flutter doctor --verbose
        {
	      echo "FLUTTER_ROOT=${{ inputs.cache-path }}"
	      echo "PUB_CACHE=${{ inputs.pub-cache-path }}"
        } >>"${GITHUB_ENV:-/dev/null}"

        {
	      echo "${{ inputs.cache-path }}/bin"
	      echo "${{ inputs.cache-path }}/bin/cache/dart-sdk/bin"
	      echo "${{ inputs.pub-cache-path }}/bin"
        } >>"${GITHUB_PATH:-/dev/null}"

    - name: Cache Flutter
      uses: actions/cache@v4
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ steps.flutter-action.outputs.CACHE-PATH }}
        key: ${{ steps.flutter-action.outputs.CACHE-KEY }}
        restore-keys: |
          ${{ steps.flutter-action.outputs.CACHE-KEY }}

    - name: Cache pub dependencies
      uses: actions/cache@v4
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}
        key: ${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}-${{ hashFiles('**/pubspec.lock') }}
          ${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}
