name: Flutter Environment
description: Setup your runner with Flutter lightweight environment
author: Artemis Kushner
branding:
  icon: maximize
  color: blue

inputs:
  flutter-version:
    description: The Flutter version to make available on the path
    required: false
    default: "stable"
  cache:
    description: Cache the Flutter SDK
    required: false
    default: "true"
  cache-key:
    description: Identifier for the Flutter SDK cache
    required: false
    default: ""
  cache-path:
    description: Flutter SDK cache path
    required: false
    default: "/home/runner/opt/flutter"
  pub-cache-key:
    description: Identifier for the Dart .pub-cache cache
    required: false
    default: ""
  pub-cache-path:
    description: Flutter pub cache path
    required: false
    default: "/home/runner/cache/pub"
  git-source:
    description: Git clone source
    required: false
    default: "https://github.com/flutter/flutter.git"

outputs:
  VERSION:
    value: "${{ steps.flutter-action.outputs.VERSION }}"
    description: The selected Flutter version
  CACHE-KEY:
    value: "${{ steps.flutter-action.outputs.CACHE-KEY }}"
    description: Key used to cache the Flutter SDK
  CACHE-PATH:
    value: "${{ steps.flutter-action.outputs.CACHE-PATH }}"
    description: Path to Flutter SDK
  PUB-CACHE-KEY:
    value: "${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}"
    description: Key used to cache the pub dependencies
  PUB-CACHE-PATH:
    value: "${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}"
    description: Path to pub cache
  GIT_SOURCE:
    value: "${{ steps.flutter-action.outputs.GIT_SOURCE }}"
    description: Git source of Flutter SDK repository to clone

runs:
  using: composite
  steps:
    # This is a cross-platform composite action that needs yq.
    # It's not preinstalled on Windows runners.
    # See https://github.com/actions/runner-images/issues/7443#issuecomment-1514597691
    - name: Make yq tool available on Windows runners
      if: runner.os == 'Windows'
      run: choco install yq
      shell: bash

    - name: Cache Flutter
      uses: actions/cache@v4
      id: cache-flutter
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.flutter-version }}
        restore-keys: |
          ${{ inputs.flutter-version }}
    - name: Cache pub dependencies
      uses: actions/cache@v4
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ inputs.pub-cache-path }}
        key: ${{ inputs.flutter-version }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ inputs.flutter-version }}-${{ hashFiles('**/pubspec.lock') }}

    - name: Set action inputs
      id: flutter-action
      if: steps.cache-flutter.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ${{ inputs.cache-path }} ${{ inputs.pub-cache-path }} && \
        # Download the Flutter SDK from the GitHub repository
        git clone -b ${{ inputs.flutter-version }} --depth 1 ${{ inputs.git-source }} ${{ inputs.cache-path }} && \
        cd ${{ inputs.cache-path }} && \
        # Set the Flutter SDK directory permissions
        git config --global --add safe.directory ${{ inputs.cache-path }} && \
        # Clean up the Flutter SDK by running the git garbage collector
        git gc --aggressive --prune=all && \
        # Disable Flutter analytics and CLI animations
        ${{ inputs.cache-path }}/bin/flutter config --disable-analytics --no-cli-animations && \
        # Precache the Flutter SDK and run the doctor
        ${{ inputs.cache-path }}/bin/flutter precache --universal && \
        ${{ inputs.cache-path }}/bin/flutter doctor --verbose
        cd ..

    - name: Echo variables
      shell: bash
      run: |
        echo "${{ inputs.cache-path }}/bin" >> "$GITHUB_PATH"
        echo "${{ inputs.pub-cache-path }}/bin" >> "$GITHUB_PATH"
        echo "${{ inputs.cache-path }}/bin/cache/dart-sdk/bin" >> "$GITHUB_PATH"


