name: test

on:
  workflow_dispatch:
    inputs:
      flutter-version:
        default: 3.29.0
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - action.yaml
      - .github/workflows/workflow.yaml
jobs:
  test_cache:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system:
          [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          flutter-version: ${{ inputs.flutter-version || '3.24.3' }}
          cache: true
      - run: dart --version
        shell: bash
      - run: flutter --version
        shell: bash
      - shell: bash
        run: |
          flutter create testproject
          echo $PATH
          find testproject/lib testproject/test -name "*.dart" ! -name "*.*.dart" -print0 | xargs -0 dart format --set-exit-if-changed --line-length 120


  test_version_file:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          flutter-version: 3.29.2
          cache: true
      - name: Verify Flutter version
        run: flutter --version | grep '3.29.2'
        shell: bash

